In [6]:
import tensorflow as tf
import numpy as np
from collections import Counter

In [7]:
from tensorflow import keras

In [8]:
tf.__version__

'2.1.0'

In [9]:
dataset = tf.data.Dataset.from_tensor_slices([[1,2,3], [4,5,6]])

In [10]:
list(dataset.as_numpy_iterator())

[array([1, 2, 3], dtype=int32), array([4, 5, 6], dtype=int32)]

In [11]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [12]:
train_images = train_images[:10000]

In [13]:
train_labels = train_labels[:10000]

In [14]:
Counter(train_labels)

Counter({9: 1000,
         0: 942,
         3: 1019,
         2: 1016,
         7: 1022,
         5: 989,
         1: 1027,
         6: 1021,
         4: 974,
         8: 990})

In [81]:
import gc
gc.collect()

9236

In [82]:
train_images = train_images / 255.0
test_images = test_images / 255.0

In [83]:
# reshape for feeding into the model
train_images1 = train_images.reshape(train_images.shape[0], 28, 28, 1)
test_images1 = test_images.reshape(test_images.shape[0], 28, 28, 1)

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

print('\ntrain_images.shape: {}, of {}'.format(train_images1.shape, train_images1.dtype))
print('test_images.shape: {}, of {}'.format(test_images1.shape, test_images1.dtype))


train_images.shape: (10000, 28, 28, 1), of float64
test_images.shape: (10000, 28, 28, 1), of float64


In [65]:
type(train_images1)

numpy.ndarray

In [29]:
train_images2 = tf.data.Dataset.from_tensor_slices((train_images, train_labels))

In [33]:
tr2 = list(train_images2.as_numpy_iterator())

In [36]:
tr2[0][0][0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
train_images1[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

#### int( (28-3)/2 ) + 1 where 28 is the width of input matrix, 3 is width of the conv filter, / by 2 for stride and add 1
* So the output is 13 x 13.  Wanted 8 such filters for Conv1
* 8 output for 10 class = 80
* 13 x 13 x 8 is flattend to 1352
* 1352 input so dense layer + 1 b layer(constant term) = 1353
* 1353 x 10 output (output class count) = 13530 parameters
* traninable parameter = 13530+80 = 13,610 trainable parameters

In [84]:
model = keras.Sequential([
  keras.layers.Conv2D(input_shape=(28,28,1), filters=8, kernel_size=3, 
                      strides=2, activation='relu', name='Conv1'),
  keras.layers.Flatten(),
  keras.layers.Dense(10, activation=tf.nn.softmax, name='Softmax')
])
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Conv1 (Conv2D)               (None, 13, 13, 8)         80        
_________________________________________________________________
flatten_13 (Flatten)         (None, 1352)              0         
_________________________________________________________________
Softmax (Dense)              (None, 10)                13530     
Total params: 13,610
Trainable params: 13,610
Non-trainable params: 0
_________________________________________________________________


In [85]:
model.compile(optimizer='Adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_images1, train_labels, epochs=30)

test_loss, test_acc = model.evaluate(test_images1, test_labels)
print('\nTest accuracy: {}'.format(test_acc))

Train on 10000 samples
Epoch 1/30
10000/10000 [==============================] - 1s 105us/sample - loss: 0.8473 - accuracy: 0.7180
Epoch 2/30
10000/10000 [==============================] - 1s 64us/sample - loss: 0.5365 - accuracy: 0.8049s - loss: 0.5473 - 
Epoch 3/30
10000/10000 [==============================] - 1s 64us/sample - loss: 0.4757 - accuracy: 0.8324
Epoch 4/30
10000/10000 [==============================] - 1s 64us/sample - loss: 0.4438 - accuracy: 0.8430
Epoch 5/30
10000/10000 [==============================] - 1s 65us/sample - loss: 0.4212 - accuracy: 0.8543
Epoch 6/30
10000/10000 [==============================] - 1s 63us/sample - loss: 0.4031 - accuracy: 0.8582
Epoch 7/30
10000/10000 [==============================] - 1s 64us/sample - loss: 0.3860 - accuracy: 0.8656
Epoch 8/30
10000/10000 [==============================] - 1s 64us/sample - loss: 0.3725 - accuracy: 0.8708
Epoch 9/30
10000/10000 [==============================] - 1s 63us/sample - loss: 0.3592 - accuracy: 0

In [71]:
model.predict(test_images1)

array([[0.07029922, 0.11324792, 0.0851632 , ..., 0.14949863, 0.09339636,
        0.08913743],
       [0.07832176, 0.11620516, 0.1012942 , ..., 0.12130687, 0.08625984,
        0.08151919],
       [0.13733609, 0.14670001, 0.09103585, ..., 0.1037167 , 0.08048975,
        0.13111794],
       ...,
       [0.09007636, 0.11892919, 0.08353793, ..., 0.1168218 , 0.10343961,
        0.09408088],
       [0.13822876, 0.12312786, 0.0895769 , ..., 0.10762322, 0.10134111,
        0.14507116],
       [0.08714482, 0.11715478, 0.09758406, ..., 0.12737855, 0.08562529,
        0.10702035]], dtype=float32)

# RNN with Keras

In [67]:
import collections
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

In [68]:
model1 = tf.keras.Sequential()
# Add an Embedding layer expecting input vocab of size 1000, and
# output embedding dimension of size 64.
model1.add(keras.layers.Embedding(input_dim=1000, output_dim=64))

# Add a LSTM layer with 128 internal units.
model1.add(keras.layers.LSTM(128))

# Add a Dense layer with 10 units.
model1.add(keras.layers.Dense(10))

model1.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          64000     
_________________________________________________________________
lstm (LSTM)                  (None, 128)               98816     
_________________________________________________________________
dense (Dense)                (None, 10)                1290      
Total params: 164,106
Trainable params: 164,106
Non-trainable params: 0
_________________________________________________________________


In [69]:
model2 = keras.Sequential([
    keras.layers.Embedding(input_dim=1000, output_dim=64, name='Embedding1'),
    keras.layers.LSTM(128, name='LSTM'),
    keras.layers.Dense(10, activation=tf.nn.softmax, name='Softmax')
])
model2.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Embedding1 (Embedding)       (None, None, 64)          64000     
_________________________________________________________________
LSTM (LSTM)                  (None, 128)               98816     
_________________________________________________________________
Softmax (Dense)              (None, 10)                1290      
Total params: 164,106
Trainable params: 164,106
Non-trainable params: 0
_________________________________________________________________
